### ISSUE TITLE
Details links (filters) should only appear if we have images for that subtype

### ISSUE THREAD

**Issue by slobulas** [nsandlin/linepig#10]
Examples:
http://linepig.fieldmuseum.org/detail.php?irn=616587  <= Ceraticelus bulbosus has images for all filters
http://linepig.fieldmuseum.org/detail.php?irn=616588  <= Certaticelus carinatus only has epigynum

**Comment by nsandlin** [comment]
To clarify further, the way it's set up now, the C carinatus epigynum image appears under the "female" filter (as well as under "epigynum"), but not under "male" or "habitus" or "palp." This is because an epigynum is an element of the female reproductive anatomy; thus that image would have DetSubject keyword values "epigynum", "female" and "genitalia."

**Comment by slobulas** [comment]
I've submitted a pull request for you to look over. Any day I can submit a PR to your repo is a good day!

**Comment by slobulas** [comment]
If you end up merging the pull request, please be sure to do a "git pull" on the Kinsey dev server, so we're all up-to-date.

**Comment by nsandlin** [comment]
I just saw that! I'm excited to look at it. Getting this issue dealt with will be a substantial step forward. ... That remark about "any day" was just darn uplifting. ... Will def do pull, since I know you don't usually work on Kinsey. Thanks!

**Comment by nsandlin** [comment]
Lovely!
