### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by slobulas** [nsandlin/linepig#21]

**Comment by slobulas** [comment]
Search on: Genus, Species and keywords.

**Comment by slobulas** [comment]
Search now implemented at /search.

**Comment by nsandlin** [comment]
Can you send me a screen shot?

**Comment by slobulas** [comment]
![screenshot 3](https://cloud.githubusercontent.com/assets/775699/20542118/dea29936-b0c5-11e6-908c-d26316da4f42.png)

**Comment by slobulas** [comment]
It's a very simple search. It includes genus, species text fields and a keywords pick-list that's auto-generated from the available subjects found on the multimedia records.

**Comment by nsandlin** [comment]
Nice!

**Comment by nsandlin** [comment]
Ah, we are doing this in the wrong place - only against the female epigynum images flagged as primary (which is all that makes it onto the main page), and as a result getting a constricted subgroup of keywords (only epigynum, female, and genitalia). This defeats the purpose, since a key function of the search - in addition to selecting subgroups - is to expose Multimedia that is otherwise inaccessible (such as, for example, male palps of species for which we do not have a female image).

If the request was made against all Multimedia objects in LinEpig, it would return the six core keywords listed in Detail pages (male, female, habitus. genitalia, palp, epigynum) and the "primary" flag, plus an ever-growing collection of other descriptors (we have apical view, ectal view, lateral view, mesal view, ventral view, so far, and possibly will shortly adding illustration, sem, face, sketch, etc.). The "view" terms are meaningless to search for, since they do not specify the part of the animal in the image (just as you can have a lateral view of your body, your head, or just your thumb). Which is why I thought we were going to hard-code the options rather than generating them view a query. 

One thought: If you want go the dynamically generated route, we could exclude, along with "primary," anything that contains (or ends with) "view." Another thought: At some point we might want to add "and" (as in "male" and "palp"); although it might be simpler to make that a separate Advanced page when we get there, than trying to build on this page for that lager.

**Comment by slobulas** [comment]
OK, that all makes sense and thank you for the detailed response. I'll figure something out!

**Comment by slobulas** [comment]
Redo the getKeywords function in the SearchController to use the keywords list provided in the emuconfig file at line 40.

**Comment by slobulas** [comment]
I've added all of the keywords back in via the emuconfig file. Is there a good way for me to query and retrieve ALL of the LinEpig records from EMu? It seems like I'm only pulling 320 records.
